name: flutter_app_builder
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  args: ^2.3.0
  crypto: ^3.0.1
  intl: any
  logger: ^2.0.1
  pub_semver: ^2.1.1
  yaml: ^3.1.0

dev_dependencies:
  archive: ^3.3.1
  lints: ^2.0.1
  msix: ^3.7.0
  test: ^1.16.0
