name: flutter_app_builder
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.0-182.1.beta <3.0.0"

# dependencies:
#   path: ^1.8.0
dependencies:
  {
    archive: ^3.3.0,
    args: ^2.3.0,
    crypto: ^3.0.1, glob: ^2.0.2,
    pub_semver: ^2.1.1,
    yaml: ^3.1.0,
  }

dev_dependencies:
  lints: ^1.0.0
  msix: ^1.0.2
  test: ^1.16.0
