name: Build Android
on:
  # Enable manual run
  workflow_dispatch:
  # Allow being called by other workflows
  workflow_call:

env:
  app-display-name: "Incredible App"
  author: "Amazing Coder"
  identifier: "com.example.incredibleapp"

jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-latest

    # ----------------------------------- Setup ------------------------------ #

    steps:
      - name: Setup Flutter
        uses: subosito/flutter-action@v2

      - name: Install Android dependencies
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Change to example directory
        run: cd ${{ github.workspace }}/example

      # TODO: Add testing for keystore config
      # - name: Configure Keystore for Android
      #   run: |
      #     echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > app/upload-keystore.jks
      #     echo "storeFile=upload-keystore.jks" >> key.properties
      #     echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> key.properties
      #     echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> key.properties
      #     echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> key.properties
      #   env:
      #     PLAY_STORE_UPLOAD_KEY: ${{ secrets.PLAY_STORE_UPLOAD_KEY }}
      #     KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
      #     KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
      #     KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}
      #   working-directory: android

      - name: Prepare for build
        run: |
          flutter upgrade
          flutter clean
          flutter pub upgrade
          flutter pub get

      # ----------------------------------- Build ---------------------------- #

      - name: Run build script
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: flutter pub run flutter_app_builder -v --platforms=android
        working-directory: example

      # After build, check if the pub log exists at ~/.pub-cache/log/pub_log.txt
      # If it does, then the build probably failed and we should print the log.
      - name: Check for build errors
        if: always()
        run: |
          if [ -f ~/.pub-cache/log/pub_log.txt ]; then
            cat ~/.pub-cache/log/pub_log.txt
            exit 1
          fi

      # ---------------------------------- Upload ---------------------------- #

      - name: Upload artifacts to workflow
        uses: actions/upload-artifact@v2
        with:
          name: android-artifacts
          path: ${{ github.workspace }}/example/output/*
