name: Build Windows
on:
  # Enable manual run
  workflow_dispatch:
  # Verify builds succeed on pull requests
  pull_request:
  # Allow being called by other workflows
  workflow_call:

env:
  app-display-name: "Incredible App"
  author: "Amazing Coder"
  identifier: "com.example.incredibleapp"
  msix-icon-path: "assets\\icons\\com.example.incredibleapp.png"

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-2019

    # ----------------------------------- Setup ------------------------------ #

    steps:
      - name: Setup Flutter
        uses: subosito/flutter-action@v2.3.0

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Change to example directory
        run: cd ${{ github.workspace }}\example

      - name: Prepare for build
        run: |
          flutter config --enable-windows-desktop
          flutter upgrade
          flutter pub get

      # ----------------------------------- Build ---------------------------- #

      - name: Run build script
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASES_TOKEN }}
        run: flutter pub run flutter_app_builder --platforms=windows
        working-directory: example

      # ---------------------------------- Upload ---------------------------- #

      - name: Upload artifacts to workflow
        uses: actions/upload-artifact@v2
        with:
          name: windows-artifacts
          path: ${{ github.workspace }}/example/output/*
