name: Run tests for Linux
on:
  workflow_dispatch:
  workflow_call:

jobs:
  test_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.5.0

      - name: Setup
        run: |
          flutter upgrade
          flutter pub get

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Run tests
        run: flutter test
