name: Run tests for Linux
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      pre-release:
        description: "Whether the test is for a pre-release"
        required: false
        default: false
        type: boolean

jobs:
  test_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Set pre-release environment variable
        if: inputs.pre-release == true
        run: echo "prerelease=true" >> $GITHUB_ENV

      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.5.0

      - name: Setup
        run: |
          flutter upgrade
          flutter pub get

      - name: Run tests
        run: flutter test
